name: test-ci
on:
  push:
    branches:
      - main
      
jobs:
  get-diff-workspace:
    runs-on: ubuntu-latest
    outputs: 
      diff-workspaces: ${{ steps.diff-workspace.outputs.workspace-matrix}}
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GHP_TOKEN }}
          fetch-depth: 2
          
      - name: Instell Package
        run: yarn install
        
      - name: Get Diff Workspace
        id: diff-workspace
        run: echo "workspace-matrix=$(yarn workspace script get-diff-workspace)" >> "$GITHUB_OUTPUT"
        
      - name: Set Output
        run: echo "Workspace:${{ steps.diff-workspace.outputs.workspace-matrix }}"
  build:
    runs-on: ubuntu-latest
    needs: [get-diff-workspace]
    strategy:
      matrix:
        workspace: ${{ fromJson(needs.get-diff-workspace.outputs.diff-workspaces) }}
    if: matrix.workspace != []
    steps:
      - name: Test Matrix
        env:
          Workspace: ${{ matrix.workspace }}
        run: echo "$Workspace"
