name: test-ci
on:
  push:
    branches:
      - main
      
jobs:
  get-diff-workspace:
    runs-on: ubuntu-latest
    outputs: 
      diff-workspaces: ${{ steps.diff-workspace.outputs.workspace-matrix}}
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GHP_TOKEN }}
          
      - name: Instell Package
        run: yarn install
        
      - name: Get Diff Workspace
        id: diff-workspace
        run: echo "workspace-matrix=$(yarn workspace script get-diff-workspace)" >> $GITHUB_OUTPUT
      - name: Get Output
        run: echo "Workspace:${{ steps.diff-workspace.outputs.workspace-matrix }}"
  build:
    runs-on: ubuntu-latest
    needs: [get-diff-workspace]
    strategy:
      matrix: ${{needs.get-diff-workspace.outputs.diff-workspace}}
    steps:
      - name: Test Matrix
        run: echo $matrix
